import * as React from 'react';

/**
 * The docs sidebar — grouped links with a mono section heading, matching the autogenerated
 * Docusaurus sidebar. Active item carries the struck left edge.
 */
export interface SidebarNavProps {
  sections?: Array<{
    label: string;
    items: Array<{ id: string; label: string; href?: string; icon?: string; trailing?: React.ReactNode }>;
  }>;
  /** Id of the current page. */
  activeId?: string;
  /** When given, links are intercepted and this is called with the item id. */
  onSelect?: (id: string) => void;
  style?: React.CSSProperties;
}

export declare function SidebarNav(props: SidebarNavProps): JSX.Element;
