import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One autogenerated sidebar over everything in docs/, ordered by the
// filesystem and any _category_.json it finds.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
