import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is written out rather than autogenerated, because every item
// carries the Lucide icon the design system names for it in
// ui_kits/docs-site/data.js. Docusaurus has no icon field, so the icon travels
// as a className and is painted as a mask — see `.menu__link[class*="sb-"]` in
// the design system's custom.css, and src/css/site.css for the per-item URLs.
const doc = (id: string, icon: string) => ({type: 'doc' as const, id, className: `sb-${icon}`});

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'The practice',
      collapsible: false,
      items: [
        doc('practice/overview', 'book-open'),
        doc('practice/principles', 'stamp'),
        doc('practice/practice-and-application', 'git-compare'),
      ],
    },
    {
      type: 'category',
      label: 'Parties',
      collapsible: false,
      items: [
        doc('parties/index', 'users'),
        doc('parties/actors', 'user'),
        doc('parties/roles', 'key-round'),
        doc('parties/personas', 'user-check'),
        doc('parties/disciplines', 'palette'),
        doc('parties/accountability', 'scale'),
      ],
    },
    {
      type: 'category',
      label: 'Work',
      collapsible: false,
      items: [
        doc('work/types', 'layers'),
        doc('work/capability', 'target'),
        doc('work/fix', 'wrench'),
        doc('work/chore', 'settings-2'),
        doc('work/question', 'circle-help'),
        doc('work/initiative', 'folder-tree'),
        doc('work/standards', 'ruler'),
        doc('work/commitment', 'calendar-clock'),
      ],
    },
    {
      type: 'category',
      label: 'Process',
      collapsible: false,
      items: [
        doc('process/index', 'route'),
        doc('process/states', 'circle-dot'),
        doc('process/capture', 'inbox'),
        doc('process/sift', 'filter'),
        doc('process/specify', 'file-check'),
        doc('process/plan', 'list-ordered'),
        doc('process/action', 'hammer'),
        doc('process/validate', 'badge-check'),
        doc('process/publish', 'send'),
      ],
    },
    {
      type: 'category',
      label: 'Apply',
      collapsible: false,
      items: [
        doc('apply/declaring-an-application', 'settings-2'),
        doc('apply/concessions', 'triangle-alert'),
        doc('apply/subtypes', 'git-fork'),
      ],
    },
    doc('terminology', 'book-marked'),
  ],
};

export default sidebars;
