window.HALLMARK_DATA = {
  nav: [
    { id: "practice", label: "Practice" },
    { id: "terminology", label: "Terminology" },
    { id: "process", icon: "route", label: "Process" },
    { id: "apply", label: "Apply" },
  ],
  sidebar: [
    { label: "The practice", items: [
      { id: "overview", icon: "book-open", label: "Overview" },
      { id: "principles", icon: "stamp", label: "Principles" },
      { id: "practice-application", icon: "git-compare", label: "Practice and application" },
    ]},
    { label: "Parties", items: [
      { id: "parties", icon: "users", label: "Parties" },
      { id: "actors", icon: "user", label: "Actors" },
      { id: "roles", icon: "key-round", label: "Roles" },
      { id: "personas", icon: "user-check", label: "Personas" },
      { id: "disciplines", icon: "palette", label: "Disciplines" },
      { id: "accountability", icon: "scale", label: "Accountability", items: [{ id: "delegation", label: "Delegation" }] },
    ]},
    { label: "Work", items: [
      { id: "work-types", icon: "layers", label: "Work types" },
      { id: "standards", icon: "ruler", label: "Standards" },
      { id: "commitment", icon: "calendar-clock", label: "Commitment" },
    ]},
    { label: "Process", items: [
      { id: "process", icon: "route", label: "The track" },
      { id: "states", icon: "circle-dot", label: "The states" },
      { id: "capture", icon: "inbox", label: "Capture" },
      { id: "sift", icon: "filter", label: "Sift" },
      { id: "specify", icon: "file-check", label: "Specify" },
      { id: "plan", icon: "list-ordered", label: "Plan" },
      { id: "action", icon: "hammer", label: "Action" },
      { id: "validate", icon: "badge-check", label: "Validate" },
      { id: "publish", icon: "send", label: "Publish" },
    ]},
  ],
  principles: [
    { name: "Provable", test: "If something is claimed, there must be evidence to prove it.", body: "Nothing advances on assertion. A specification that was never seen to pass is an intention with a filename." },
    { name: "Derived", test: "If something can be determined from the record, it must not be decided.", body: "What a change touches decides what it must satisfy — nobody rules a change small enough to skip something." },
    { name: "Traceable", test: "If something is claimed, decided or moved, there must be a path to what produced it.", body: "One door in, identifiable actors, and a recorded reason at every gate." },
    { name: "Invariant", test: "Whatever the size of the work, or the kind of actor, the same process applies.", body: "The practice runs all-human, all-agent, or any mix, without alteration." },
  ],
  terms: [
    { id: "actor", term: "Actor", kind: "Party", definition: "A human or an agent — the thing that actually holds a role. Every actor must be distinctly identifiable.", seeAlso: [{ label: "Role", href: "#role" }, { label: "Delegation", href: "#delegation" }] },
    { id: "application", term: "Application", kind: "Boundary", definition: "One technology-specific instantiation of the practice — the trackers, pipelines, templates and agents through which a system actually runs it.", seeAlso: [{ label: "Practice", href: "#practice" }] },
    { id: "capability", term: "Capability", kind: "Work type", definition: "An outcome a named persona can achieve. The only work type that adds to what the system can be said to do.", seeAlso: [{ label: "Specification", href: "#specification" }] },
    { id: "capture", term: "Capture", kind: "Act", definition: "Recording a request at the door. Capture does nothing else: it does not type the request, judge it, or agree to it.", seeAlso: [{ label: "Sift", href: "#sift" }] },
    { id: "concession", term: "Concession", kind: "Record", definition: "To concede is to state that a standard has not been met, name who accepted that, and proceed anyway. A concession is not an exception to the practice — it is the practice working.", seeAlso: [{ label: "Standard", href: "#standard" }] },
    { id: "criterion", term: "Criterion", kind: "Evidence", definition: "One statement of what would make the work right, written at Specify before anything is built.", seeAlso: [{ label: "Specification", href: "#specification" }] },
    { id: "practice", term: "Practice", kind: "Boundary", definition: "The interface — what must hold, who may act, and how work travels. Normative and technology-agnostic: it names no tool.", seeAlso: [{ label: "Application", href: "#application" }] },
    { id: "role", term: "Role", kind: "Party", definition: "An interface — Worker, Verifier, Sentinel, Decider — of which the actor is the implementation. There are four, and the practice fixes them.", seeAlso: [{ label: "Permission", href: "#permission" }] },
    { id: "sift", term: "Sift", kind: "Act", definition: "Ruling on a request — the first act on the change, and the first that requires a role. Two things settle and no more: what type the request carries, and whether it will be done at all.", seeAlso: [{ label: "Request", href: "#request" }] },
    { id: "specification", term: "Specification", kind: "Evidence", definition: "An executable statement of what the system should do. The only thing that can prove a capability.", seeAlso: [{ label: "Capability", href: "#capability" }] },
    { id: "standard", term: "Standard", kind: "Standard", definition: "A statement of what must hold, expressed as a floor. Standards stack by union: a layer may add or constrain, never contradict.", seeAlso: [{ label: "Concession", href: "#concession" }] },
    { id: "touch", term: "Touch", kind: "Derivation", definition: "What a change reaches — the parts of the system it alters, and whatever depends on them. Declared by the plan.", seeAlso: [{ label: "Plan", href: "#plan" }] },
  ],
  acts: [
    ["Capture", "Anyone", "A request"],
    ["Sift", "Worker", "A typed item, agreed to be done"],
    ["Specify", "Worker", "Specifications that fail"],
    ["Plan", "Worker", "An ordered route, and a declared touch"],
    ["Action", "Worker", "The change, and a result for every criterion"],
    ["Validate", "The persona, or a recorded stand-in", "A judgement on the outcome"],
    ["Publish", "Worker", "A delivered result, confirmed — and the state complete"],
  ],
  roles: [
    ["Worker", "Advances the work", "Accumulates — the only role that does"],
    ["Verifier", "Confirms it against a standard", "Denied — never saw the doing"],
    ["Sentinel", "Watches for drift, staleness and cost", "Outside any work session"],
    ["Decider", "Commits money, risk or a promise", "Denied — decides from the record"],
  ],
};
